api:
  noaa:
    # Get token from https://www.ncdc.noaa.gov/cdo-web/token
    token: ${NOAA_TOKEN}
  eia:
    # Get API key from https://www.eia.gov/opendata/register.php
    api_key: ${EIA_API_KEY}

cities:
  - name: New York
    state: New York
    noaa_station_id: GHCND:USW00094728
    eia_region_code: NYIS
  - name: Chicago
    state: Illinois
    noaa_station_id: GHCND:USW00094846
    eia_region_code: PJM
  - name: Houston
    state: Texas
    noaa_station_id: GHCND:USW00012960
    eia_region_code: ERCO
  - name: Phoenix
    state: Arizona
    noaa_station_id: GHCND:USW00023183
    eia_region_code: AZPS
  - name: Seattle
    state: Washington
    noaa_station_id: GHCND:USW00024233
    eia_region_code: SCL
